CREATE DATABASE PI_PROJETO;

USE PI_PROJETO;


CREATE TABLE cliente (ID INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR (45),
cnpj CHAR (14) NOT NULL,
CPF CHAR (11) NOT NULL UNIQUE,
senha VARCHAR (70) NOT NULL UNIQUE);
 
 
 CREATE TABLE insumo (ID INT PRIMARY KEY AUTO_INCREMENT,
 nome VARCHAR (45),
 fabricante VARCHAR (100) NOT NULL,
 custo DECIMAL (10,2) NOT NULL,
 toneladas DECIMAL (20,2));
 
 
 CREATE TABLE hectare (ID INT PRIMARY KEY AUTO_INCREMENT,
 comprimento_m2 FLOAT (20,2) NOT NULL,
 largura_m2 DECIMAL (20,2) NOT NULL,
 area_m2 DECIMAL (10,2) NOT NULL,
 hectare DECIMAL (20,2) NOT NULL);
 
 
 CREATE TABLE canavial (ID INT PRIMARY KEY AUTO_INCREMENT,
 comprimento FLOAT (10,2) NOT NULL,
 largura DECIMAL (10,2) NOT NULL,
 area_m2 DECIMAL (10,2) NOT NULL, 
 volume INT NOT NULL);
 
 
 CREATE TABLE sensor (ID INT PRIMARY KEY AUTO_INCREMENT,
 tipo_sensor VARCHAR (45) NOT NULL,
 dis_leitura INT NOT NULL,
 unidade_medida VARCHAR (2) DEFAULT 'cm',
 data_hora DATETIME);
 
 
